### ISSUE TITLE
problems with bitcoin.service

### ISSUE THREAD

**Issue by Fonta1n3** [k3tan25/ubuntu-node-box#1]
Hello,

I am having issues with the bitcoin.service file. The only difference is I installed bitcoin core from the ppa, everything else is identical as far a folder structure is concerned.

I get this error when executing:

`sudo systemctl start bitcoind`

`Job for bitcoind.service failed because the control process exited with error code.
See "systemctl status bitcoind.service" and "journalctl -xe" for details.`

I then execute `journalctl -xe`

And get:

`Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
-- The process /usr/local/bin/bitcoind could not be executed and failed.
-- 
-- The error number returned by this process is 2.
Mar 25 16:58:51 hodlco-node systemd[2809]: bitcoind.service: Failed to execute command: No such file or directory
Mar 25 16:58:51 hodlco-node systemd[2809]: bitcoind.service: Failed at step EXEC spawning /usr/local/bin/bitcoind: No such file or directory
-- Subject: Process /usr/local/bin/bitcoind could not be executed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The process /usr/local/bin/bitcoind could not be executed and failed.
-- 
-- The error number returned by this process is 2.
Mar 25 16:58:51 hodlco-node systemd[2830]: bitcoind.service: Failed to execute command: No such file or directory
Mar 25 16:58:51 hodlco-node systemd[2830]: bitcoind.service: Failed at step EXEC spawning /usr/local/bin/bitcoind: No such file or directory
-- Subject: Process /usr/local/bin/bitcoind could not be executed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The process /usr/local/bin/bitcoind could not be executed and failed.
-- 
-- The error number returned by this process is 2.
Mar 25 16:58:52 hodlco-node systemd[2854]: bitcoind.service: Failed to execute command: No such file or directory
Mar 25 16:58:52 hodlco-node systemd[2854]: bitcoind.service: Failed at step EXEC spawning /usr/local/bin/bitcoind: No such file or directory
-- Subject: Process /usr/local/bin/bitcoind could not be executed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The process /usr/local/bin/bitcoind could not be executed and failed.
-- 
-- The error number returned by this process is 2.
Mar 25 16:58:52 hodlco-node systemd[2880]: bitcoind.service: Failed to execute command: No such file or directory
Mar 25 16:58:52 hodlco-node systemd[2880]: bitcoind.service: Failed at step EXEC spawning /usr/local/bin/bitcoind: No such file or directory
-- Subject: Process /usr/local/bin/bitcoind could not be executed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The process /usr/local/bin/bitcoind could not be executed and failed.
-- 
-- The error number returned by this process is 2.`

Please any help would be greatly appreciated! I have trouble-shot it like crazy and no luck.

**Comment by k3tan172** [comment]
It appears the issue is that your startup script is looking for the program at ```/usr/local/bin/bitcoind``` but it is not installed at that location. The PPA may have installed it at ```/usr/bin/bitcoind``` instead. You can confirm this by typing ```whereis bitcoind``` in your terminal. Edit your ```bitcoind.service``` file to ensure the reference to ```/usr/local/bin/bitcoind``` is changed to ```/usr/bin/bitcoind``` and try it again. The location should match the output of ```whereis bitcoind```. Let me know how that goes.

**Comment by Fonta1n3** [comment]
Ok, I shutdown bitcoind then changed the service file to the correct directory `/usr/bin/bitcoind`

then run `sudo systemctl daemon-reload` and `sudo systemctl start bitcoind`

it returns same error so i run `journalctl -xe`

and it returns (all the same errors as before assuming thats just the history) with this new error at the bottom:

`Mar 25 18:49:30 hodlco-node bitcoind[22716]: Error: Cannot obtain a lock on data directory /mnt/volume_fra1_02/Bitcoin/testnet3. Bitcoin Core is probably already running.
Mar 25 18:49:31 hodlco-node bitcoind[22742]: Error: Cannot obtain a lock on data directory /mnt/volume_fra1_02/Bitcoin/testnet3. Bitcoin Core is probably already running.
Mar 25 18:49:31 hodlco-node bitcoind[22767]: Error: Cannot obtain a lock on data directory /mnt/volume_fra1_02/Bitcoin/testnet3. Bitcoin Core is probably already running.
Mar 25 18:49:31 hodlco-node bitcoind[22793]: Error: Cannot obtain a lock on data directory /mnt/volume_fra1_02/Bitcoin/testnet3. Bitcoin Core is probably already running.
Mar 25 18:49:31 hodlco-node bitcoind[22819]: Error: Cannot obtain a lock on data directory /mnt/volume_fra1_02/Bitcoin/testnet3. Bitcoin Core is probably already running`

For sure bitcoind is not running when i try and restart the service.

**Comment by Fonta1n3** [comment]
The issue was I had a hidden process trying to access bitcoind, thank you for you help and great tutorial
