### ISSUE TITLE
bitcoin-cli not working

### ISSUE THREAD

**Issue by wchancao** [k3tan25/ubuntu-node-box#10]
Hi, I finally managed to start bitcoind on boot using systemd service file, but i got a very weird issue, bitcoind is running but bitcoin-cli commands are not working... The outputs from the terminal are these:

> wae@node:~$ sudo systemctl status bitcoind
● bitcoind.service - Bitcoin daemon
   Loaded: loaded (/etc/systemd/system/bitcoind.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-01-15 09:31:38 -04; 3min 24s ago
  Process: 803 ExecStart=/usr/local/bin/bitcoind -daemon -pid=/run/bitcoind/bitcoind.pid -conf=/home/wae/.bitcoin/bitcoin.conf -datadir=/mnt/1TBHDD/Bitcoin (code=exited,
  Process: 756 ExecStartPre=/bin/chgrp wae /etc/bitcoin (code=exited, status=0/SUCCESS)
 Main PID: 861 (bitcoind)
    Tasks: 8 (limit: 3389)
   CGroup: /system.slice/bitcoind.service
           └─861 /usr/local/bin/bitcoind -daemon -pid=/run/bitcoind/bitcoind.pid -conf=/home/wae/.bitcoin/bitcoin.conf -datadir=/mnt/1TBHDD/Bitcoin
ene 15 09:31:33 node systemd[1]: Starting Bitcoin daemon...
ene 15 09:31:38 node systemd[1]: bitcoind.service: Can't open PID file /run/bitcoind/bitcoind.pid (yet?) after start: No such file or directory
ene 15 09:31:38 node systemd[1]: Started Bitcoin daemon.

> wae@node:~$ bitcoin-cli getblockchaininfo
error: Could not connect to the server 127.0.0.1:8332
Make sure the bitcoind server is running and that you are connecting to the correct RPC port.

>wae@node:~$ bitcoin-qt
Error: Cannot obtain a lock on data directory /mnt/1TBHDD/Bitcoin. Bitcoin Core is probably already running.

If I stop the bitcoind service, and start it again with bitcoind -daemon, everything works well... Hop you can help me!

**Comment by k3tan172** [comment]
Can you show me your ```bitcoind.service``` file?

**Comment by wchancao** [comment]
I managed to solve the issue commenting the ExecStartPre line... Now Im struggling with the btc-rpc-explorer service file!!! LOL

**Comment by k3tan172** [comment]
Yeah I noticed that ExecStartPre line. It might be worthwhile watching the video series to see it being built out if you haven't already seen it. https://www.youtube.com/channel/UC93aLHD4fxvLPP3KSOV0TIg/playlists
