### ISSUE TITLE
btc-rpc-explorer service file

### ISSUE THREAD

**Issue by wchancao** [k3tan25/ubuntu-node-box#11]
Hello, as i said in the other issue, im having problems now with the btc-rpc-explorer service file, my service file is as follow: 

> [Unit]
Description=btc-rpc-explorer
After=bitcoind.service
Requires=bitcoind.service
[Service]
EnvironmentFile=/home/wae/.config/btc-rpc-explorer.env
ExecStart=/home/wae/.nvm/versions/node/v13.3.0/bin/btc-rpc-explorer
RuntimeDirectory=btc-rpc-explorer
PIDFile=/run/btc-rpc-explorer/explorer.pid
User=wae
Group=wae
Type=simple
KillMode=process
Restart=on-failure
RestartSec=60
PrivateTmp=true
ProtectSystem=full
NoNewPrivileges=true
PrivateDevices=true
[Install]
WantedBy=bitcoind.service

And the ouput from the terminal is this:

> wae@node:~/.config$ sudo systemctl status btc-rpc-explorer.service
● btc-rpc-explorer.service - btc-rpc-explorer
   Loaded: loaded (/etc/systemd/system/btc-rpc-explorer.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2020-01-15 22:00:12 -04; 51s ago
  Process: 3453 ExecStart=/home/wae/.nvm/versions/node/v13.3.0/bin/btc-rpc-explorer (code=exited, status=127)
 Main PID: 3453 (code=exited, status=127)
ene 15 22:00:12 node systemd[1]: btc-rpc-explorer.service: Main process exited, code=exited, status=127/n/a
ene 15 22:00:12 node systemd[1]: btc-rpc-explorer.service: Failed with result 'exit-code'.

If i type btc-rpc-explorer on the terminal the explorer works ok in the browser, i googled about code 127 on systemd and it said that was something related to ExecStart was not a executable file...

**Comment by k3tan172** [comment]
try ```/home/wae/.nvm/versions/node/v13.3.0/bin/btc-rpc-explorer``` in terminal and see what error comes up. also try ```whereis btc-rpc-explorer``` in terminal and pointing your service file to the output of that.

**Comment by wchancao** [comment]
Here is the output:

> wae@node:~/.config$ /home/wae/.nvm/versions/node/v13.3.0/bin/btc-rpc-explorer 
Loading env file: /home/wae/.config/btc-rpc-explorer.env
Loading RPC cookie file: /mnt/1TBHDD/Bitcoin/.cookie
  btcexp:app Starting BTC RPC Explorer, v1.1.8 +0ms
  btcexp:app Connecting to RPC node at 127.0.0.1:8332 +2ms
  btcexp:app Trying to verify RPC connection... +32ms
  btcexp:app RPC Connected: version=190001 (/Satoshi:0.19.0.1/), protocolversion=70015, chain=main, services=[NETWORK, WITNESS, NETWORK_LIMITED] +385ms

>wae@node:~/.config$ whereis btc-rpc-explorer
btc-rpc-explorer: /home/wae/.nvm/versions/node/v13.3.0/bin/btc-rpc-explorer

**Comment by k3tan172** [comment]
Deactivate these items in the service by putting a # in front of them. Reload and try it again.
PrivateTmp=true
ProtectSystem=full
NoNewPrivileges=true
PrivateDevices=true

**Comment by wchancao** [comment]
Nope, that didnt work, same output:

>wae@node:~$ sudo systemctl daemon-reload 
wae@node:~$ sudo systemctl start btc-rpc-explorer
wae@node:~$ sudo systemctl status btc-rpc-explorer
● btc-rpc-explorer.service - btc-rpc-explorer
   Loaded: loaded (/etc/systemd/system/btc-rpc-explorer.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2020-01-15 22:25:19 -04; 10s ago
  Process: 3751 ExecStart=/home/wae/.nvm/versions/node/v13.3.0/bin/btc-rpc-explorer (code=exited, status=127)
 Main PID: 3751 (code=exited, status=127)
ene 15 22:25:19 node systemd[1]: btc-rpc-explorer.service: Main process exited, code=exited, status=127/n/a
ene 15 22:25:19 node systemd[1]: btc-rpc-explorer.service: Failed with result 'exit-code'.

**Comment by k3tan172** [comment]
OK try ```journalctl -xe``` is there an output that relates to btc-rpc-explorer? Also try user=root and group=root, just to see if that works.

**Comment by wchancao** [comment]
Yes, 

>wae@node:~$ journalctl -xe
-- Unit btc-rpc-explorer.service has finished shutting down.
ene 16 08:07:43 node systemd[1]: Started btc-rpc-explorer.
-- Subject: Unit btc-rpc-explorer.service has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit btc-rpc-explorer.service has finished starting up.
-- 
-- The start-up result is RESULT.
ene 16 08:07:43 node btc-rpc-explorer[6157]: /usr/bin/env: ‘node’: No such file or directory
ene 16 08:07:43 node systemd[1]: btc-rpc-explorer.service: Main process exited, code=exited, status=127/n/a
ene 16 08:07:43 node systemd[1]: btc-rpc-explorer.service: Failed with result 'exit-code'.
ene 16 08:08:12 node gdm-password][6162]: gkr-pam: unlocked login keyring
ene 16 08:08:13 node gnome-software[1503]: no app for changed ubuntu-dock@ubuntu.com
ene 16 08:08:13 node gnome-software[1503]: no app for changed ubuntu-appindicators@ubuntu.com
ene 16 08:08:13 node gvfsd-metadata[2405]: g_udev_device_has_property: assertion 'G_UDEV_IS_DEVICE (device)' failed
ene 16 08:08:13 node gvfsd-metadata[2405]: g_udev_device_has_property: assertion 'G_UDEV_IS_DEVICE (device)' failed
ene 16 08:08:14 node gnome-shell[1153]: [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1.57/org/ayatana/NotificationItem/software_update_available
ene 16 08:08:14 node gnome-shell[1153]: [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1.57/org/ayatana/NotificationItem/livepatch
ene 16 08:08:43 node systemd[1]: btc-rpc-explorer.service: Service hold-off time over, scheduling restart.
ene 16 08:08:43 node systemd[1]: btc-rpc-explorer.service: Scheduled restart job, restart counter is at 758.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Automatic restarting of the unit btc-rpc-explorer.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
ene 16 08:08:43 node systemd[1]: Stopped btc-rpc-explorer.
-- Subject: Unit btc-rpc-explorer.service has finished shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit btc-rpc-explorer.service has finished shutting down.
ene 16 08:08:43 node systemd[1]: Started btc-rpc-explorer.
-- Subject: Unit btc-rpc-explorer.service has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit btc-rpc-explorer.service has finished starting up.
-- 
-- The start-up result is RESULT.
ene 16 08:08:43 node btc-rpc-explorer[6175]: /usr/bin/env: ‘node’: No such file or directory
ene 16 08:08:43 node systemd[1]: btc-rpc-explorer.service: Main process exited, code=exited, status=127/n/a
ene 16 08:08:43 node systemd[1]: btc-rpc-explorer.service: Failed with result 'exit-code'.

**Comment by wchancao** [comment]
Changing user and group to root didnt work neither...

**Comment by wchancao** [comment]
I solved the issue adding the absolute path of node.js at the beginning of ExecStart, like this:

>ExecStart=/home/wae/.nvm/versions/node/v13.3.0/bin/node /home/wae/.nvm/versions/node/v13.3.0/bin/btc-rpc-explorer

And leaving user and group as wae
