### ISSUE TITLE
Note to update electrum server address to mainnet 

### ISSUE THREAD

**Issue by bipsrocks** [k3tan25/ubuntu-node-box#2]
I've been struggling with the electrum personal server for a while not getting it to connect. 
Staring very hard today I realised it was trying to connect to testnet. 
I removed the 2 on teh port number and everything worked great, I'd suggest a note to make this obvious as this is a great guide for noob and this is a simple mistake!

**Comment by k3tan172** [comment]
I'm not sure what you mean by removing the 2 on the port number? Which file is this in? Are you referring to the config.cfg file in the electrum-personal-server folder?
