### ISSUE TITLE
RPC Credential issue - possibly due to Tor Configuration?

### ISSUE THREAD

**Issue by ghost** [k3tan25/ubuntu-node-box#5]
I've managed to get a bitcoind service running, but I cannot use `bitcoin-cli` commands to query or manage the service as I get an 

`error: Could not locate RPC credentials. No authentication cookie could be found, and RPC password is not set.  See -rpcpassword and -stdinrpcpass.  Configuration file: (/home/<username>/.bitcoin/bitcoin.conf)`

There are two differences between my build and your node box, the first being a tor-only bitcoind setup, the second that instead of an ssd for the OS I'm running the OS and node in a 3 disk raid5 setup.

Here is the top of my `bitcoind.service` file: 

```Unit]
Description=Bitcoin daemon
After=network.target

[Service]
ExecStart=/usr/local/bin/bitcoind -daemon \
                            -pid=/run/bitcoind/bitcoind.pid \
                            -conf=/home/<username>/.bitcoind/bitcoin.conf \
                            -datadir=/home/<username>/.bitcoind

# Make sure the config directory is readable by the service user
PermissionsStartOnly=true
ExecStartPre=/bin/chgrp <username> /etc/bitcoin

# Process management
####################

Type=forking
PIDFile=/run/bitcoind/bitcoind.pid
Restart=on-failure
TimeoutStopSec=600

# Directory creation and permissions
####################################

# Run as bitcoin:bitcoin -> changed to debian-tor:<username>
User=<username>
Group=debian-tor
```

my  `bitcoin.conf` file looks like this:

```txindex=0
onlynet=onion
maxconnections=20
proxy=127.0.0.1:9050
#listen=1

# [core]
# run in the background as a daemon and accept commands
daemon=1


bind=127.0.0.1
dbcache=100
maxmempool=100
par=3
```

**Comment by k3tan172** [comment]
In your bitcoin.conf file add the following line and change the path to wherever your .cookie file is. You can see the file in terminal by going to the directory and typing ```ll```

```rpccookiefile=/home/ketan/.bitcoin/.cookie```

restart bitcoind and let me know how that goes.

**Comment by k3tan172** [comment]
Also I have noticed your conf file in your service file is: conf=/home/username/.bitcoind/bitcoin.conf

Can you double check that? it should be ```/home/username/.bitcoin/bitcoin.conf```

**Comment by ghost** [comment]
You were correct. The `conf=/home/username/.bitcoind/bitcoin.conf` was incorrect. Unfortunately, now that I've changed that, and added `rpccookiefile=/home/<username>/.bitcoin/.cookie` to my `bitcoin.conf` file, the systemctl service won't start.

When I reload the service using:

```
sudo systemctl daemon-reload

sudo systemctl start bitcoind

sudo systemctl status bitcoind
```

I get the following error:

```
 bitcoind.service - Bitcoin daemon
   Loaded: loaded (/etc/systemd/system/bitcoind.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-10-30 05:04:20 PDT; 4s ago
  Process: 5574 ExecStart=/usr/local/bin/bitcoind -daemon -pid=/run/bitcoind/bitcoind.pid -conf=/home/<username>/.bitcoin/bitcoin.conf -datadir=/home/<username>/.bitcoin (code=exited, status=1/FAILURE)
  Process: 5562 ExecStartPre=/bin/chgrp <username> /etc/bitcoin (code=exited, status=0/SUCCESS)
```

I then ran `journalctl -xe` to check the service log and the following line appeared interesting:

```
-- Unit bitcoind.service has begun starting up.
Oct 30 05:07:00 machine bitcoind[5871]: ************************
Oct 30 05:07:00 machine bitcoind[5871]: EXCEPTION: N5boost10filesystem16filesystem_errorE
Oct 30 05:07:00 machine bitcoind[5871]: boost::filesystem::status: Permission denied: "/home/<username>/.bitcoin"
Oct 30 05:07:00 machine bitcoind[5871]: bitcoin in AppInit()
Oct 30 05:07:00 machine systemd[1]: bitcoind.service: Control process exited, code=exited status=1
```
Could it be that systemctl doesn't have permission to access the `.bitcoin` folder?

I've tried changing the `bitcoind.service` user and group to:

```
# Run as bitcoin:bitcoin -> changed to debian-tor:<username>
User=<username>
Group=<username>
```
Whereas previously I had the group set to the system tor group. This is not working atm.

**Comment by k3tan172** [comment]
Try removing these two lines
```
PermissionsStartOnly=true
ExecStartPre=/bin/chgrp <username> /etc/bitcoin
```
User= and Group= should be the same username.

**Comment by ghost** [comment]
Done. Bitcoin service is still failing to start, and the `journalctl -xe` readout is showing:

```
-- Unit bitcoind.service has begun starting up.
Oct 30 10:25:10 machine bitcoind[8894]: ************************
Oct 30 10:25:10 machine bitcoind[8894]: EXCEPTION: N5boost10filesystem16filesystem_errorE
Oct 30 10:25:10 machine bitcoind[8894]: boost::filesystem::status: Permission denied: "/home/<username>/.bitcoin"
Oct 30 10:25:10 machine bitcoind[8894]: bitcoin in AppInit()
```

So it seems to be the same error, a Permission Denited for the /home/<username>/.bitcoin folder

**Comment by k3tan172** [comment]
Try user=root and group=root

**Comment by ghost** [comment]
I've tried many permutations and none have been successful. But to follow your suggestions, when I make the following changes to  the `bitcoind.service` file:

```
# Make sure the config directory is readable by the service user
PermissionsStartOnly=true
#ExecStartPre=/bin/chgrp <username> /etc/bitcoin

User=root
Group=root
```

I now get the following error in the `journalctl -xe` readout:
```
machine bitcoind[3091]: Error: Specified data directory "/home/<username>/.bitcoin" does not exist.
```
This doesn't make sense because if I navigate to the `.bitcoin` directory that holds the blockchain and conf file and type `pwd` it returns: `/home/<username>/.bitcoin`

**Comment by k3tan172** [comment]
OK - remove the ```rpccookiefile=``` line. Go back to your usual ```user=``` and ```group=```
If that doesn't work and you're still getting permission errors, perhaps try a virtual machine (virtualbox.org) and load a fresh install of Ubuntu on that.

**Comment by ghost** [comment]
Thanks for your help debugging.

I have finally found the problem:

In the `# Hardening measures` section

```
# Deny access to /home, /root and /run/user
ProtectHome=true
```

this must be set to `false` to allow access to the home directory. I think this wasn't a problem for your setup because the .conf file, which is in your home, wasn't being written to, instead, you were writing blocks to your `/mount` which wasn't hardened by this option.

I got the idea by running bitcoind as a service using the much more basic `bitcoind.service` template here: https://github.com/bitcoin/bitcoin/blob/2d782ab2ce30bf106e34cd3288c9082ac04022f9/contrib/init/bitcoind.service

Great guide and amazing support!

This template does not contain the system hardening measures listed in yours. I suspect that the problem came from the 


specification.
