### ISSUE TITLE
Bitcoin daemon not working

### ISSUE THREAD

**Issue by wchancao** [k3tan25/ubuntu-node-box#7]
Hi, im following your guide and having a weird problem, bitcoin daemon sometimes auto-starts but sometimes it doesnt... When it doesnt autostarts after a reboot, the error message is the following:

wae@node:~$ sudo systemctl status bitcoind
● bitcoind.service - Bitcoin daemon
   Loaded: loaded (/etc/systemd/system/bitcoind.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2019-11-14 17:44:15 -04; 2h 40min ago
  Process: 804 ExecStart=/usr/local/bin/bitcoind -daemon -pid=/run/bitcoind/bitcoind.pid -conf=/home/wae/.bitcoin/bitcoin.conf -datadir=/mnt/1TBHDD/Bit
  Process: 799 ExecStartPre=/bin/chgrp wae /etc/bitcoin (code=exited, status=0/SUCCESS)

nov 14 17:44:15 node systemd[1]: Starting Bitcoin daemon...
nov 14 17:44:15 node systemd[1]: bitcoind.service: Control process exited, code=exited status=1
nov 14 17:44:15 node systemd[1]: bitcoind.service: Failed with result 'exit-code'.
nov 14 17:44:15 node systemd[1]: Failed to start Bitcoin daemon.
nov 14 17:44:15 node systemd[1]: bitcoind.service: Service hold-off time over, scheduling restart.
nov 14 17:44:15 node systemd[1]: bitcoind.service: Scheduled restart job, restart counter is at 5.
nov 14 17:44:15 node systemd[1]: Stopped Bitcoin daemon.
nov 14 17:44:15 node systemd[1]: bitcoind.service: Start request repeated too quickly.
nov 14 17:44:15 node systemd[1]: bitcoind.service: Failed with result 'exit-code'.
nov 14 17:44:15 node systemd[1]: Failed to start Bitcoin daemon.

My bitcoind.service is this:

[Unit]
Description=Bitcoin daemon
After=network.target

[Service]
ExecStart=/usr/local/bin/bitcoind -daemon \
                            -pid=/run/bitcoind/bitcoind.pid \
                            -conf=/home/wae/.bitcoin/bitcoin.conf \
                            -datadir=/mnt/1TBHDD/Bitcoin

PermissionsStartOnly=true
ExecStartPre=/bin/chgrp wae /etc/bitcoin

Type=forking
PIDFile=/run/bitcoind/bitcoind.pid
Restart=always

User=wae
Group=wae

RuntimeDirectory=bitcoind
RuntimeDirectoryMode=0710

ConfigurationDirectory=bitcoin
ConfigurationDirectoryMode=0710

StateDirectory=bitcoind
StateDirectoryMode=0710

PrivateTmp=true

ProtectSystem=full

ProtectHome=false

NoNewPrivileges=true

PrivateDevices=true

MemoryDenyWriteExecute=true

[Install]
WantedBy=multi-user.target

Hope you can help me! Thanks!

**Comment by k3tan172** [comment]
Hey, did you want to compare your service file with that of the bitcoin core repository? You can find it [here](https://github.com/bitcoin/bitcoin/blob/master/contrib/init/bitcoind.service). Try different combinations. On first glance, I see you've got ```Restart=always```, whilst the repository has ```Restart=on-failure```. There's also ```TimeoutStopSec=600``` missing. Try that and see how you go?

**Comment by wchancao** [comment]
Yes, I have tried a lot of combinations and none of them works, I have also tried another service files i've found googling... Dont you think its better to autostart bitcoind using crontab? What are the differences? Is it better or worse?

**Comment by k3tan172** [comment]
I haven't tried using crontab so I don't know. From what I understand crontab is suited for more 'recurring' style commands that you want done every x sec/min/hour/day. If it works for you, go for it! The idea is to figure out a way to get bitcoind going on startup of the machine.
