### ISSUE TITLE
.lightning folder not created

### ISSUE THREAD

**Issue by wchancao** [k3tan25/ubuntu-node-box#8]
Hi,
I have a problem installing c-lightning, you mention that a .lightning folder should be created after compiling and installing, but i didnt get that folder created automatically... sudo make and sudo make install ends with no errors... Should i just create the folder manually?

**Comment by k3tan172** [comment]
Are you installing the new c-lightning v0.8.0? I haven't upgraded my c-lightning yet, but there should be a folder ```/home/user/.lightning/bitcoin``` upon installation. Or it might be installed in ```/root/.lightning```?

There are other methods of installing c-lightning as well such as the PPA. Check https://github.com/ElementsProject/lightning#installation

I'm using the instructions here: https://github.com/ElementsProject/lightning/blob/master/doc/INSTALL.md

Try creating the folder manually, and seeing if ```lightningd``` works.

**Comment by wchancao** [comment]
Folder automatically created after running `lightningd` for the first time.
