### ISSUE TITLE
Question re. btc-rpc-explorer init script

### ISSUE THREAD

**Issue by shawnyeager** [k3tan25/ubuntu-node-box#9]
First, thanks a ton, @k3tan172, for this and the YouTube series; hugely valuable.

All has gone smoothly for me with the exception of the init script for `btc-rpc-explorer` under Pop_OS/Ubuntu 19.10. I'm seeing the following:

```
shawn@ceres ~ ❯❯❯ sudo systemctl start btc-rpc-explorer
[sudo] password for shawn:
Job for btc-rpc-explorer.service failed because of unavailable resources or another system error.
See "systemctl status btc-rpc-explorer.service" and "journalctl -xe" for details.
```

Here's my init script:

```
[Unit]
Description=btc-rpc-explorer
After=bitcoind.service
Requires=bitcoind.service

[Service]
EnvironmentFile=/home/shawn/.confg/btc-rpc-explorer.env
ExecStart=/usr/bin/btc-rpc-explorer

RuntimeDirectory=btc-rpc-explorer
PIDFile=/run/btc-rpc-explorer/explorer.pid
User=shawn
Group=shawn

Type=simple
KillMode=process
Restart=on-failure
RestartSec=60

# Hardening measures
####################

# Provide a private /tmp and /var/tmp.
PrivateTmp=true

# Mount /usr, /boot/ and /etc read-only for the process.
ProtectSystem=full

# Disallow the process and all of its children to gain
# new privileges through execve().
NoNewPrivileges=true

# Use a new /dev namespace only populated with API pseudo devices
# such as /dev/null, /dev/zero and /dev/random.
PrivateDevices=true

[Install]
WantedBy=bitcoind.service
```

Unfortunately, `journalactl -xe` provides no insights.

I am able to execute `btc-rpc-explorer` successfully outside of the init script.

**Comment by k3tan172** [comment]
I would recommend 'commenting' the hardening measures in your service file one by one to deactivate them from the script to see if that works. Start with changing the line

```NoNewPrivileges=true```

by putting a # infront of it

```#NoNewPrivileges=true```

Save it, close it.

Remember to execute

```sudo systemctl daemon-reload```

Then start it back up again

```sudo systemctl start btc-rpc-explorer```

If that doesn't work, try commenting out ```ProtectSystem=full```

**Comment by shawnyeager** [comment]
Thanks. I tried each individually and both together, but see the same problem. Not urgent, of course. Just wanted to see if anyone's seen the same.

**Comment by k3tan172** [comment]
```EnvironmentFile=/home/shawn/.confg/btc-rpc-explorer.env```

spelling mistake! it should be .config not .confg

**Comment by shawnyeager** [comment]
Oh, man, the worst kind of user error. 

That did it. Thanks!

**Comment by k3tan172** [comment]
Haha all good. I'm kinda annoyed at myself for not picking that up the first time!
